# Generated by Django 3.1.1 on 2020-09-03 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^([a-zA-Z]){2}$', 'State must be 2 letters. Example, "CA".')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Zip code must be 5 digits.')]),
        ),
    ]
